# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 15, 30, 9, 416675, tzinfo=utc)),
        ),
    ]
